spring.application.name=user-service
server.port=8082

# --- gRPC Server ---
grpc.server.port=9094

# --- Service Discovery ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=123
# Liquibase
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

# --- Hibernate Logging (??????? ??? ??????? ?????????? PESSIMISTIC_WRITE) ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# SQL
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG

# --- Kafka ---
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- Swagger & OpenAPI ---
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

# --- Security ---
spring.security.jwt.secret=jdl4wFp9GsQK3RJC9KLMWRPO09qR4V5H0bj36vLhYsXj2V2bkI0vWlE2V3c8vd0a97Hq4L1p1c8l2n0a7n0a7g==

# --- gRPC Logging ---
logging.level.net.devh.boot.grpc.server=DEBUG
logging.level.com.inovexx=DEBUG

server.forward-headers-strategy=framework
