spring.application.name=user-service

server.port=8082

auth.service.url=http://localhost:8081

spring.security.jwt.secret=jdl4wFp9GsQK3RJC9KLMWRPO09qR4V5H0bj36vLhYsXj2V2bkI0vWlE2V3c8vd0a97Hq4L1p1c8l2n0a7n0a7g==

spring.jpa.hibernate.ddl-auto=none

springdoc.swagger-ui.path=/swagger-ui.html
