spring.application.name=order-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=create
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

# --- Service Discovery (Eureka) ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- gRPC Server (gRPC) ---
grpc.server.port=9090

# --- gRPC Clients (discovery) ---
# inventory-service
grpc.client.inventory-service.address=discovery:///inventory-service
grpc.client.inventory-service.negotiation-type=plaintext

# user-service
grpc.client.user-service.address=discovery:///user-service
grpc.client.user-service.negotiation-type=plaintext

# --- Kafka Producer (Outbox Scheduler) ---
spring.kafka.producer.bootstrap-servers=localhost:9092
kafka.topic.order-events=order.events
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- Resilience4j: Circuit Breaker ---
resilience4j.circuitbreaker.instances.inventoryService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventoryService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventoryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventoryService.permittedNumberOfCallsInHalfOpenState=3

# --- Resilience4j: Retry ---
resilience4j.retry.instances.userService.maxAttempts=3
resilience4j.retry.instances.userService.waitDuration=2s
#gRPC
resilience4j.retry.instances.userService.retryExceptions=io.grpc.StatusRuntimeException

# --- Security ---
spring.security.jwt.secret=jdl4wFp9GsQK3RJC9KLMWRPO09qR4V5H0bj36vLhYsXj2V2bkI0vWlE2V3c8vd0a97Hq4L1p1c8l2n0a7n0a7g==

# --- Logging ---
logging.level.root=INFO
logging.level.com.inovexx=DEBUG
logging.level.io.github.resilience4j=DEBUG

# swagger-ui
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs