spring.application.name=order-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
#none
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

# --- Service Discovery (Eureka) ---

# Eureka
eureka.client.enabled=true

# gRPC
eureka.instance.metadata-map.grpc.port=${grpc.server.port}
# grpc.client
grpc.client.order-service.address=discovery:///order-service
grpc.client.order-service.negotiation-type=plaintext
grpc.client.order-service.enable-keep-alive=true
grpc.client.order-service.keep-alive-without-calls=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.health-check-url-path=/actuator/health

# --- gRPC Server (gRPC) ---
grpc.server.port=9090

# --- gRPC Clients (discovery) ---
# inventory-service
grpc.client.inventory-service.address=discovery:///inventory-service
grpc.client.inventory-service.negotiation-type=plaintext

# user-service
grpc.client.user-service.address=discovery:///user-service
grpc.client.user-service.negotiation-type=plaintext

# --- Kafka Producer (Outbox Scheduler) ---
spring.kafka.producer.bootstrap-servers=localhost:9092
kafka.topic.order-events=order.events
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- Resilience4j: Circuit Breaker ---
resilience4j.timelimiter.instances.inventoryService.timeoutDuration=2s
resilience4j.retry.instances.userService.enable-exponential-backoff=true
resilience4j.retry.instances.userService.exponential-backoff-multiplier=2

resilience4j.circuitbreaker.instances.inventoryService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventoryService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventoryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventoryService.permittedNumberOfCallsInHalfOpenState=3

# --- Resilience4j: Retry ---
resilience4j.retry.instances.userService.maxAttempts=3
resilience4j.retry.instances.userService.waitDuration=2s
#gRPC
resilience4j.retry.instances.userService.retryExceptions=io.grpc.StatusRuntimeException

# --- Security ---
spring.security.jwt.secret=jdl4wFp9GsQK3RJC9KLMWRPO09qR4V5H0bj36vLhYsXj2V2bkI0vWlE2V3c8vd0a97Hq4L1p1c8l2n0a7n0a7g==

# swagger-ui
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.retry.backoff.ms=1000
spring.kafka.producer.enable-idempotence=true

# --- Logging ---
logging.level.root=INFO
logging.level.com.inovexx=DEBUG
logging.level.org.springframework.transaction=WARN
logging.level.org.springframework.orm.jpa=WARN
# Hibernate ? SQL
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
logging.level.org.hibernate.engine.transaction=WARN
logging.level.org.springframework.scheduling=INFO
logging.level.com.zaxxer.hikari=WARN
# Resilience4j - Circuit Breaker
logging.level.io.github.resilience4j=INFO
# Kafka
logging.level.org.springframework.kafka=WARN
