spring.application.name=order-service
server.port=8085
# --- Database & Liquibase ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/order_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123}
# Liquibase
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
# --- Service Discovery (Eureka) ---
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true
# --- gRPC Server & Discovery Metadata ---
grpc.server.port=9090
eureka.instance.metadata-map.grpc.port=${grpc.server.port}
# --- gRPC Clients ---
# : Eureka
grpc.client.inventory-service.address=discovery:///inventory-service
grpc.client.user-service.address=discovery:///user-service
grpc.client.inventory-service.negotiation-type=plaintext
grpc.client.user-service.negotiation-type=plaintext
# --- Kafka Producer ---
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka.topic.order-events=order.events
# String, JSON
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
# Reliability
spring.kafka.producer.acks=all
spring.kafka.producer.enable-idempotence=true
# Outbox
spring.kafka.producer.retries=3
# --- Outbox Scheduler Settings ---
# outbox
app.outbox.interval=5000
app.outbox.batch-size=50
app.outbox.max-retries=5
# --- Resilience4j ---
resilience4j.timelimiter.instances.inventoryService.timeoutDuration=2s
resilience4j.retry.instances.userService.maxAttempts=3
# --- Security & Swagger ---
spring.security.jwt.secret=${JWT_SECRET:jdl4wFp9GsQK3RJC9KLMWRPO09qR4V5H0bj36vLhYsXj2V2bkI0vWlE2V3c8vd0a97Hq4L1p1c8l2n0a7n0a7g==}
springdoc.swagger-ui.path=/swagger-ui.html
# --- Logging ---
logging.level.com.inovexx=DEBUG
logging.level.org.springframework.kafka=INFO
# Outbox
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO