# ???????? ????????? ??????????
spring.application.name=api-gateway
server.port=8088
# ????????? Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# ????????? ????? ???????? ??????? ?? ?? ?????? ? Eureka
spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
# ????????? Redis (???????????? ??? Rate Limiting ??? ???????? ??????)
spring.data.redis.host=localhost
spring.data.redis.port=6379
# ???????????? ? JWT
# ?????????, ??? ???? ?????? ????????? ? ???, ??? ???????????? ? ?????? ?????????????
spring.security.jwt.secret=jdl4wFp9GsQK3RJC9KLMWRPO09qR4V5H0bj36vLhYsXj2V2bkI0vWlE2V3c8vd0a97Hq4L1p1c8l2n0a7n0a7g==
# ??????????? (????????????? ??? ??????? ?????????????)
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.client.loadbalancer=TRACE
logging.level.org.springframework.security=DEBUG
# ????????? SpringDoc Swagger UI
# ???????????? ??? ????????? ???????????? ?? ?????????????
springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/api/auth/v3/api-docs
springdoc.swagger-ui.urls[1].name=user-service
springdoc.swagger-ui.urls[1].url=/api/users/v3/api-docs
springdoc.swagger-ui.urls[2].name=inventory-service
springdoc.swagger-ui.urls[2].url=/api/inventory/v3/api-docs
springdoc.swagger-ui.urls[3].name=product-service
springdoc.swagger-ui.urls[3].url=/api/products/v3/api-docs
springdoc.swagger-ui.urls[4].name=order-service
springdoc.swagger-ui.urls[4].url=/api/orders/v3/api-docs
springdoc.swagger-ui.display-query-params-ui=true
springdoc.cache.disabled=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.layout=StandaloneLayout
springdoc.swagger-ui.deep-linking=true
# ????????? Gateway (WebFlux)
# ?????????? ????? ??? ????????? ?????? Spring Cloud Gateway
spring.cloud.gateway.x-forwarded.enabled=true
spring.cloud.gateway.server.webflux.x-forwarded.enabled=true
spring.cloud.gateway.filter.remove-non-proxy-headers.headers=
spring.cloud.gateway.server.webflux.filter.remove-non-proxy-headers.headers=
# ?????????? ???????
spring.cloud.gateway.default-filters[0]=PreserveHostHeader

spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=10s


