spring.application.name=notification-service
server.port=8086
# --- Service Discovery (Eureka) ---
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
# --- Kafka Configuration (Consumer & Producer) ---
# Docker/K8s
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka.topic.notification-events=notification.events

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.inovexx.*

spring.kafka.consumer.properties.spring.json.use.type.headers=false
# Retry Topics, DLT
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# --- MongoDB ---
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/notification-db}
# --- Redis & Cache ---
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis
# Redisson
spring.redisson.address=redis://${spring.data.redis.host}:${spring.data.redis.port}
# --- Email Configuration ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:your-email@gmail.com}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8
# JavaMail Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
# --- FreeMarker ---
spring.freemarker.enabled=true
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh
spring.freemarker.charset=UTF-8
spring.freemarker.content-type=text/html

spring.freemarker.cache=false
# --- Task Execution (Async Email & Kafka) ---
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=100
spring.task.execution.thread-name-prefix=mail-task-
# --- Custom App Logic (Retry & Rate Limit) ---
app.notification.retry.attempts=3
app.notification.retry.delay-ms=300000
app.notification.rate-limit.capacity=5
app.notification.rate-limit.duration-minutes=10
app.notification.support-email=support@inovexx.com
# --- Actuator & Monitoring ---
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
# --- Logging ---
logging.level.root=INFO
logging.level.org.apache.kafka=WARN
logging.level.com.inovexx.notificationservice=DEBUG
logging.level.org.springframework.mail=DEBUG
# Bucket4j
logging.level.io.github.bucket4j=DEBUG
