spring.application.name=notification-service
server.port=8086

# --- Service Discovery ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- Kafka Configuration (Consumer & Producer) ---
spring.kafka.bootstrap-servers=localhost:9092
kafka.topic.notification-events=notification.events
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
# JSON, Kafka
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.inovexx.*

# --- MongoDB ---
spring.data.mongodb.uri=mongodb://localhost:27017/notification-db

# --- Redis & Cache ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# --- Email Configuration ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
#  export MAIL_PASSWORD=xxxx
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

# JavaMail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000

# FreeMarker
spring.freemarker.enabled=true
# src/main/resources/templates)
spring.freemarker.template-loader-path=classpath:/templates/
# .ftlh
spring.freemarker.suffix=.ftlh
# UTF-8
spring.freemarker.charset=UTF-8
spring.freemarker.content-type=text/html
spring.freemarker.cache=false

# --- Actuator ---
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

logging.level.org.springframework.mail=DEBUG
