syntax = "proto3";

option java_multiple_files = true;

option java_package = "com.inovexx.order_service.grpc";

// 1. Описание сервиса
service InventoryService {
  rpc ReserveStock (ReserveRequest) returns (ReserveResponse);

  // Метод для отката (компенсации)
  rpc CancelReservation (CancelReserveRequest) returns (CancelReserveResponse);
}

// 2. Описание сообщений для ReserveStock
message ReserveRequest {
  string product_id = 1;
  int32 quantity = 2;
}

message ReserveResponse {
  bool success = 1;
  string message = 2;
}

// 3. Описание сообщений для CancelReservation (ОТСЮДА БЫЛА ОШИБКА)
message CancelReserveRequest {
  string product_id = 1;
  int32 quantity = 2;
}

message CancelReserveResponse {
  bool success = 1;
}
