spring.application.name=user-service

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.kafka.producer.bootstrap-servers=localhost:9092
# Docker: spring.kafka.producer.bootstrap-servers=kafka:9092

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.security.jwt.secret=jdl4wFp9GsQK3RJC9KLMWRPO09qR4V5H0bj36vLhYsXj2V2bkI0vWlE2V3c8vd0a97Hq4L1p1c8l2n0a7n0a7g==

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.groups.enabled=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.root=INFO

server.forward-headers-strategy=framework

springdoc.swagger-ui.enabled=true

