spring.application.name=auth-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.security.jwt.secret=jdl4wFp9GsQK3RJC9KLMWRPO09qR4V5H0bj36vLhYsXj2V2bkI0vWlE2V3c8vd0a97Hq4L1p1c8l2n0a7n0a7g==

springdoc.swagger-ui.path=/swagger-ui.html
